project_id: "369101"
base_path: .
base_url: "https://api.crowdin.com"
preserve_hierarchy: true
files:
  - source: websites/**/*.json
    ignore:
      - websites/**/metadata.json
      - websites/**/package.json
      - websites/**/package-lock.json
    translation: websites/**/%locale%/%original_file_name%
    dest: Activities/%original_file_name%

  - source: websites/general.json
    translation: websites/%locale%/general.json
    dest: Activities/%original_file_name%
