name: Feature Request
description: Request a new feature for an existing activity
labels: [feature request]
body:
  - type: markdown
    attributes:
      value: |
        Before requesting a new feature, ensure your request hasn't already been
        submitted before. If it has, reply to the open issue instead.
  - type: input
    id: activity_name
    attributes:
      label: Activity name
    validations:
      required: true
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Description
      description: Describe in detail what would you like to see added to the activity and why.
  - type: textarea
    id: alternatives
    validations:
      required: false
    attributes:
      label: Alternatives
      description: Any alternatives to what you stated in the description
  - type: textarea
    id: additional_context
    validations:
      required: false
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
