name: Assets Updater

on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.json'

jobs:
  check-and-run:
    if: github.repository_owner == 'PreMiD'
    name: Update assets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm

      - name: Install pmd
        run: npm ci

      - name: Update assets
        env:
          CDN_TOKEN: ${{ secrets.CDN_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          # Configure git
          git config --local user.email "contact@premid.app"
          git config --local user.name "PreMiD Automations"

          # Run PMD update-assets command
          npx pmd update-assets
