name: Stale
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Stale
        uses: actions/stale@v9
        with:
          days-before-stale: 60
          days-before-pr-stale: 14
          stale-issue-message: |
            This issue has been marked as stale because it has been inactive for over 60 days.
            If this is still relevant, please leave a comment to let us know.
            Otherwise, this issue may be closed automatically in 7 days.
          close-issue-message: |
            This issue has been automatically closed due to inactivity for over 60 days.
            If you believe this issue is still relevant, feel free to reopen it or create a new one with updated information.
          stale-pr-message: |
            This PR has been marked as stale because it has been inactive for over 14 days.
            If you believe this PR is still relevant, please leave a comment to let us know.
            Otherwise, this PR may be closed automatically in 7 days.
          close-pr-message: |
            This PR has been automatically closed due to inactivity for over 14 days.
            If you believe this PR is still relevant, feel free to reopen it or create a new one with updated information.
          stale-pr-label: inactive
          stale-issue-label: inactive
          only-issue-labels: bug,needs repro
          operations-per-run: 1000
